// Single source of truth for the site.
// Use plain ASCII punctuation throughout (no em-dashes or curly quotes) so
// every browser / font fallback renders the text cleanly.
window.PROFILE = {
  name: "Goshtasb Shahriari Mehr",
  shortName: "Goshtasb Shahriari",
  initials: "GS",
  title: "ML / AI Software Engineer - Spatial Analytics - PhD",
  tagline: "Spatial AI for the next city.",
  oneLine:
    "I build LLM agents, spatial machine learning, and agent-based simulations - and ship them as real software: browser-native geo-agents, production dashboards, and research platforms.",
  photo: "../assets/photo.jpeg",
  emails: {
    uf: "g.shahriarimehr@ufl.edu",
    personal: "goshtasbshahriari@gmail.com",
  },
  // Keep the original `email` for legacy mockups
  email: "g.shahriarimehr@ufl.edu",
  phone: "+1 (352) 727-2728",
  location: "Gainesville, Florida, USA",
  cvUrl: "assets/cv.pdf",
  social: {
    github: "https://github.com/GoshtasbSh",
    linkedin: "https://www.linkedin.com/in/goshtasb-shahriari-mehr-1826bb130/",
    scholar: "https://scholar.google.com/citations?user=Bruj7TQAAAAJ&hl=en",
    orcid: "https://orcid.org/0000-0001-5867-9675",
  },

  // Numbers shown under the hero. Keep these honest and easy to defend.
  heroStats: [
    { n: "04", k: "DEGREES" },
    { n: "13", k: "SYSTEMS BUILT" },
    { n: "05", k: "LIVE DEPLOYMENTS" },
    { n: "2026", k: "PhD DEFENDED" },
  ],

  // ------------ Reel definitions (hero) ------------
  reels: [
    {
      key: "path",
      label: "Spatial path",
      sub: "4 degrees - 2012 to 2026",
      kicker: "// Reel 01 - Spatial path",
      title: "A spatial mind,",
      titleEm: "in motion.",
      body:
        "Four degrees over fourteen years on one line of inquiry: how do people, places, and policy interact in space. From civil-geomatics engineering to GIS, urban analytics, and machine learning - and now to shipping the software that does the analysis.",
      skills: [
        "BSc - Civil-Geomatics - KNTU",
        "MSc - GIS - University of Tehran",
        "MSc - ECE - University of Florida (dual degree)",
        "PhD - Urban Analytics - University of Florida",
      ],
      color: "#9bc6ff",
    },
    {
      key: "ml",
      label: "Machine Learning",
      sub: "ML, computer vision, Bayesian modeling",
      kicker: "// Reel 02 - Machine Learning",
      title: "Teaching maps",
      titleEm: "to learn.",
      body:
        "Machine learning and statistical modeling applied to urban data, imagery, and surveys. Transfer learning and segmentation on real imagery; a seven-model Bayesian and causal-inference portfolio (IRT, causal forests, DAG discovery) deployed as a live dashboard; spatial statistics (Moran's I, Getis-Ord Gi*, Kulldorff scan) served from a FastAPI engine.",
      skills: [
        "PyTorch - TensorFlow - scikit-learn",
        "PyMC - ArviZ - BART - causal inference",
        "PySAL / ESDA spatial statistics",
        "UF Machine Learning Certificate (ECE)",
      ],
      color: "#22d3ee",
    },
    {
      key: "abm",
      label: "Agent-based modeling",
      sub: "PhD dissertation (defended 2026)",
      kicker: "// Reel 03 - Agent-based modeling",
      title: "Cities, modeled",
      titleEm: "as agents.",
      body:
        "My PhD dissertation populates Jacksonville Health Zone 1 with synthetic households and simulates how they reach food under four policy interventions. Then I rebuilt it as a generative twin, where each household's decision is made by an LLM with episodic and word-of-mouth memory - same world, only the decision mechanism changed.",
      skills: [
        "Python - Mesa-Geo - GeoPandas - Shapely",
        "Calibrated discrete-choice model (error 0.095)",
        "Sobol sensitivity - 50-seed Monte Carlo",
        "Generative ABM - LLM agents + RAG memory",
      ],
      color: "#ffba3b",
    },
    {
      key: "llm",
      label: "Agent AI and LLMs",
      sub: "GeoChatBot, Local Glean, RAG",
      kicker: "// Reel 04 - Agent AI and LLMs",
      title: "LLM agents,",
      titleEm: "that ship.",
      body:
        "Production-grade LLM engineering, not demos. GeoChatBot runs a plan-then-execute agent over 28 typed tools entirely in the browser (DuckDB-WASM, hybrid RAG, zero backend). Local Glean runs a 9-node LangGraph pipeline with a fail-closed anti-hallucination verifier on a university on-premise gateway. Both are live.",
      skills: [
        "LLM agents - tool calling - structured output",
        "RAG: embeddings + BM25 + reciprocal rank fusion",
        "LangGraph - pgvector - LiteLLM - eval harnesses",
        "Prompt-injection defense - fail-closed verifiers",
      ],
      color: "#ff6dd9",
    },
  ],

  bio: [
    "I am an ML / AI software engineer with a spatial background. In 2026 I defended my PhD in Design, Construction & Planning at the University of Florida, and in December 2025 I completed a dual MSc in Electrical & Computer Engineering at UF, taken alongside the PhD to bring modern machine learning, computer vision, and LLM / agent-AI methods into the urban-analytics work.",
    "What I actually do is build systems. Over the last two years I have shipped a browser-native LLM agent for spatial analysis (GeoChatBot), a FERPA-safe on-premise AI email assistant with a LangGraph multi-agent pipeline (Local Glean), two production geospatial research platforms (KeyStone Heights and FieldSurvey), and a Bayesian re-analysis of a coastal-community survey deployed as an interactive dashboard - all solo, all with real test suites and formal security or pre-publication audits.",
    "My dissertation evaluates food-access scenarios in Jacksonville Health Zone 1 with a calibrated agent-based model, then re-implements it as a generative ABM where each household's decision is made by an LLM with episodic and social memory. Before UF I earned an MSc in Geographic Information Science from the University of Tehran and a BSc in Civil-Geomatics Engineering from K. N. Toosi University of Technology.",
  ],

  interests: [
    { label: "Agent AI and LLMs", note: "Agents - RAG - evals - LLM safety" },
    { label: "Agent-Based Modeling", note: "Food access - generative ABM" },
    { label: "Machine Learning", note: "Certified - UF + Coursera" },
    { label: "Bayesian & Causal Inference", note: "PyMC - BART - DAG discovery" },
    { label: "Spatial Data Engineering", note: "PostGIS - GeoPandas - DuckDB" },
    { label: "Full-Stack Engineering", note: "Next.js - FastAPI - Supabase" },
    { label: "Computer Vision", note: "Segmentation - classification" },
    { label: "Location-Based Services", note: "Recommender systems - POIs" },
  ],

  affiliations: [
    {
      role: "Graduate Research Assistant",
      org: "Florida Institute for Built Environment Resilience (FIBER), UF",
      years: "Jan 2022 - Present",
    },
    {
      role: "Graduate Research Assistant",
      org: "Disasters, Trust, and Social Change Lab, UF",
      years: "Jun 2023 - Present",
    },
    {
      role: "Graduate Research Assistant",
      org: "iAdapt - International Center for Adaptation Planning & Design",
      years: "Aug 2025 - Feb 2026",
      detail: "FDOT District 5: review and comparative analysis of existing transport analyses for Central Florida. Advisor: Dr. Zhong-Ren Peng.",
    },
  ],

  education: [
    {
      degree: "PhD, Design, Construction & Planning",
      school: "University of Florida",
      years: "2022 - 2026",
      note: "Dissertation defended in 2026. Evaluating Food Access Scenarios in Jacksonville Health Zone 1 with Agent-Based Modeling.",
    },
    {
      degree: "MSc, Electrical & Computer Engineering",
      school: "University of Florida",
      years: "2023 - 2025",
      note: "Dual degree alongside the PhD. GPA 3.81 / 4.00.",
    },
    {
      degree: "MSc, Geographic Information Science",
      school: "University of Tehran",
      years: "2016 - 2019",
      note: "Thesis grade: Excellent. Two peer-reviewed papers published from this thesis.",
    },
    {
      degree: "BSc, Civil-Geomatics Engineering",
      school: "K. N. Toosi University of Technology",
      years: "2012 - 2016",
      note: "Thesis: Evaluation of methods for 3D cadaster.",
    },
  ],

  // ------------ Projects ------------
  // category is used for the filter chips. Keep to the five below.
  projectCategories: ["AI / LLM", "Geospatial", "Research", "Full-stack", "ML / CV"],

  projects: [
    {
      key: "geochatbot",
      name: "GeoChatBot",
      tag: "Browser-native LLM agent",
      category: "AI / LLM",
      year: "2026",
      status: "Live - open source",
      role: "Sole developer",
      summary:
        "An embeddable AI agent that answers plain-English questions about your own spatial and tabular data with zero backend. Files never leave the browser: DuckDB-WASM does the analysis, an LLM plans before it acts, and you approve the plan before anything runs.",
      detail: [
        "GeoChatBot ships as a single Web Component (<geo-chatbot>) distributed three ways: a one-line script embed, a standalone hosted app, and a headless dashboard-injection mode that emits typed events into a host page's own UI. It is bring-your-own-LLM and works across Groq, Google Gemini, Anthropic, OpenAI-compatible endpoints, and a self-hosted university vLLM gateway - five provider families, each hand-written against its native HTTP API with no vendor SDKs.",
        "The agent architecture is deliberately conservative: plan-then-execute with an explicit human approval gate (not free-running ReAct), constrained tool-calling over 28 typed Zod-validated tools (no eval, no code generation), and a critic loop that self-heals failed steps. Answers are checked by a deterministic claim-grounding verifier that recomputes argmax/argmin over the actually-computed table, plus a Chain-of-Verification corrector.",
        "Retrieval is a full hybrid RAG pipeline running in the browser: 384-dim MiniLM sentence embeddings via transformers.js/WASM, an IndexedDB vector store, hand-written BM25, and Reciprocal Rank Fusion. The geospatial engine is DuckDB-WASM with its spatial extension over Apache Arrow - spatial joins, buffers, dissolve, convex hull, nearest-neighbor, choropleth classification - rendered with MapLibre GL and deck.gl.",
      ],
      highlights: [
        "Plan-then-execute agent with human approval gate over 28 typed, Zod-validated tools",
        "Five LLM provider families normalized behind one interface, four native tool-calling protocols",
        "In-browser hybrid RAG: MiniLM embeddings + BM25 + Reciprocal Rank Fusion",
        "Prompt-injection defense via per-session datamarking fences (Microsoft Spotlighting)",
        "Replaced DuckDB's ST_Distance_Sphere with exact-haversine SQL macros after measuring a ~25% error",
        "Python + Playwright eval harness benchmarking 5+ models, with a Markdown leaderboard",
      ],
      metrics: [
        { k: "TypeScript", v: "23.4K LOC" },
        { k: "Unit tests", v: "800+" },
        { k: "Agent tools", v: "28" },
        { k: "LLM providers", v: "5" },
      ],
      stack: ["TypeScript", "Lit / Web Components", "DuckDB-WASM", "Apache Arrow", "transformers.js", "MapLibre GL", "deck.gl", "Vite", "Next.js 15", "Playwright"],
      url: "https://github.com/GoshtasbSh/GeoChatBot",
      demoUrl: "https://geochatbot-eight.vercel.app/app",
      demoLabel: "Live demo",
      links: [
        { label: "Landing page", url: "https://geochatbot-eight.vercel.app" },
        { label: "Docs", url: "https://geochatbot-eight.vercel.app/docs" },
        { label: "Eval leaderboard", url: "https://geochatbot-eight.vercel.app/evals" },
      ],
      note:
        "Advanced spatial statistics (Moran's I, Getis-Ord, Voronoi, hex-bin) and true CRS reprojection are deliberate roadmap stubs, not shipped features.",
      featured: true,
    },
    {
      key: "glean",
      name: "Local Glean",
      tag: "On-premise AI email assistant",
      category: "AI / LLM",
      year: "2026",
      status: "Live - add-in open source",
      role: "Sole developer",
      summary:
        "A self-hosted, FERPA-safe AI email assistant: it triages an inbox with a two-stage classifier and drafts replies in the user's own writing voice using a multi-agent LangGraph pipeline - with every model call running on the university's on-premise LLM gateway, so no email content ever leaves campus systems.",
      detail: [
        "The drafting engine is a 9-node LangGraph state machine with Postgres checkpointing (crash-resumable): load context, classify intent, retrieve exemplars, load project memory, draft, verify, polish, write outputs - with a redraft loop on the first verifier failure and mark-for-review on the second. Drafts stream token-by-token to the browser over Server-Sent Events and are never auto-sent.",
        "Triage is a two-stage cascade: a vector kNN classifier over already-labeled embeddings with a multi-gate confidence rule (neighbor count, majority agreement, similarity floor, and a margin gate) that abstains to an LLM stage with rule-RAG, where the user's plain-English rules are embedded and retrieved into the prompt. User corrections become labeled neighbors, so it learns with no retraining.",
        "The safety story is the interesting part: a fail-closed verifier combining a deterministic regex gate (banned phrases, hallucinated-commitment spans) with an LLM semantic check, plus a prompt-injection sanitizer doing Unicode NFKC normalization, zero-width stripping, Cyrillic/Greek confusable folding, and untrusted-content tagging. A formal 10-phase pre-deployment security audit returned NO-GO with 14 deploy blockers; all 14 plus 4 re-test issues were remediated and live-verified to a final GO.",
        "A later pivot re-ported the entire ML/NLP stack (embeddings, kNN, k-means, stylometry, BM25, reciprocal rank fusion) to TypeScript so it runs client-side inside an Outlook task pane with in-memory-only data custody. Numerical parity with the Python reference is proven to 1e-9 by a committed parity oracle - which surfaced two real float bugs: naive JS summation flipping near-tie cosine rankings (fixed with Neumaier compensated summation) and sklearn's BLAS silhouette expansion error band.",
      ],
      highlights: [
        "9-node LangGraph agent pipeline with Postgres checkpointing and SSE token streaming",
        "Two-stage classifier (vector kNN cascade to LLM + rule-RAG) - 96.7% measured accuracy",
        "Fail-closed anti-hallucination verifier - 100% first-try pass in pre-deployment evaluation",
        "Formal 10-phase security audit: NO-GO with 14 blockers to GO, all live-verified",
        "Entire ML pipeline re-ported to browser TypeScript with 1e-9 numerical parity",
        "5-model on-premise serving stack behind LiteLLM with Langfuse tracing and a regression-diffing eval harness",
      ],
      metrics: [
        { k: "Code", v: "~32.7K LOC" },
        { k: "Automated tests", v: "~660" },
        { k: "Triage accuracy", v: "96.7%" },
        { k: "Draft latency", v: "~4 s median" },
      ],
      stack: ["Python", "FastAPI", "LangGraph", "PostgreSQL + pgvector", "SQLAlchemy 2.0", "Redis / arq", "Next.js 16", "React 19", "Office.js", "MSAL", "LiteLLM", "Docker"],
      url: "https://github.com/GoshtasbSh/Glean_add-in",
      demoUrl: "https://goshtasbsh.github.io/Glean_add-in/",
      demoLabel: "Open the add-in",
      note:
        "Phase 1 shipped is email triage and drafting. Meeting transcription (Whisper) is designed and partially shipped in the add-in free layer; the full Meetings module is Phase 2. The server application is a private repo; the Outlook add-in is public.",
      featured: true,
    },
    {
      key: "food-abm",
      name: "Food-Access ABM + Generative Twin",
      tag: "PhD dissertation - simulation",
      category: "Research",
      year: "2026",
      status: "Dissertation defended 2026",
      role: "Sole developer",
      summary:
        "A spatially-explicit agent-based simulation of how ~48,000 households in Jacksonville Health Zone 1 reach food, calibrated against real census and BLS survey data - then re-engineered into a generative ABM where each household's decision is made by an LLM with two-tier RAG memory.",
      detail: [
        "The reference model is a Mesa-Geo agent-based simulation over 45 real census tracts. Each household agent decides whether to shop (income-calibrated day thresholds and dwindling food supply) and where to shop (grocery stores, corner stores, food hubs, mobile pantries, home delivery) by maximizing a calibrated random-utility function over distance, price, quality, and convenience. Four policy interventions are evaluated against the baseline: a new grocery store, a food-hub and corner-store network, mobile pantries, and subsidized delivery.",
        "Rigor was the point. Seven parameters were calibrated in two phases against real spending, corner-store share, food-insecurity, and travel-distance targets, reaching a calibration error of 0.095. Results come from up to 50-seed Monte Carlo replication with triple RNG seeding, Sobol global sensitivity analysis (first, total, and second-order indices with bootstrap CIs), and effect sizes reported with bootstrap 95% CIs, Cohen's d, and Welch t-tests.",
        "The generative twin subclasses the reference model rather than reimplementing it, so exactly one copy of the simulated world exists and the claim 'only the decision mechanism changed' is provable - a RULE mode reproduces the original byte-for-byte under golden-regression tests. On top of that sits a four-rung ablation ladder (rule, LLM, LLM + episodic memory, LLM + social memory) with a two-tier RAG memory: recency-weighted episodic retrieval over sentence-transformer embeddings, and word-of-mouth retrieval over a spatial k-nearest-neighbor social graph.",
        "Making a stochastic LLM scientifically reproducible required temperature-0 with a fixed seed, content-addressed prompt-versioned response caching, tenacity retry with backoff, graceful rule-argmax fallbacks so multi-hour runs never crash, and a deterministic offline mock client for CI.",
      ],
      highlights: [
        "~48,044 households across 45 census tracts; 500 households x 365 days x up to 50 seeds",
        "Calibrated discrete-choice random-utility model, calibration error 0.095 across 7 parameters",
        "Sobol global sensitivity analysis (SALib) with PRCC / SRC / bootstrap corroboration",
        "Four-rung LLM ablation ladder with episodic + word-of-mouth RAG memory",
        "Byte-identical golden-regression parity between the rule-based and generative models",
        "Matched-seed counterfactual policy evaluation and a five-tier validation harness (pattern-oriented modeling)",
      ],
      metrics: [
        { k: "Python", v: "~36K LOC" },
        { k: "Tests", v: "~280" },
        { k: "Households", v: "48K modeled" },
        { k: "Policies", v: "4 evaluated" },
      ],
      stack: ["Python", "Mesa 3 / Mesa-Geo", "GeoPandas", "Shapely", "SciPy KDTree", "sentence-transformers", "SALib", "Dash / Plotly", "Docker"],
      url: null,
      demoUrl: null,
      note:
        "The large-scale evidence runs shipped so far were generated with a deterministic offline mock LLM client for reproducibility, with live smoke tests verified against the real Llama-3.1-8B endpoint; the full-scale real-LLM production run targets a GPU environment.",
      featured: true,
    },
    {
      key: "keystone",
      name: "KeyStone Heights Research Platform",
      tag: "GIS platform - production",
      category: "Geospatial",
      year: "2026",
      status: "Live in production",
      role: "Sole designer and developer",
      summary:
        "A full-stack, GIS-driven community health research platform for a UF lab: an offline-capable field-survey PWA for door-to-door surveyors, plus a desktop geospatial analytics dashboard over 11,319 property parcels with an LLM chat analyst that can drive the live map.",
      detail: [
        "The pipeline starts with Florida's statewide cadastral File Geodatabase, ingested with GeoPandas using an attribute push-down filter, reprojected to EPSG:4326 with pyproj, and simplified with topology-preserving Douglas-Peucker so ~11,300 parcel polygons ship efficiently to the web as GeoJSON.",
        "Survey responses are geocoded and matched to households through a four-tier cascade: exact parcel-address match, fuzzy parcel match, US Census geocoder with snap-to-nearest-parcel over a Shapely STRtree spatial index with Haversine refinement, then raw-coordinate fallback - each result tagged with its provenance and confidence. Record linkage joins responses to canvassing contacts by parcel identity rather than GPS proximity, a deliberate choice because Qualtrics records where a survey was submitted, not where the household is.",
        "Researchers query the data through a Groq Llama-3.3-70B analyst that returns a fenced block of map-control commands (highlight streets, filter by IAQ symptom, show choropleth, zoom to street) which the frontend executes - an agentic 'LLM drives the UI' pattern with a deterministic keyword fallback and prompt-injection hardening via an allowlist.",
        "The backend exists in two forms kept in lock-step by a CI-style parity test: a FastAPI monolith for heavy local GeoPandas processing and a 12-function Vercel serverless port engineered to fit the platform's bundle and function ceilings. Security was hardened through a formal 46-finding pre-deploy audit covering row-level security, SECURITY DEFINER hardening, CSP headers, ephemeral guest auth, and PII minimization at the API boundary.",
      ],
      highlights: [
        "11,319 parcels ingested from state cadastral GIS and rendered as an interactive choropleth",
        "4-tier geocoding cascade with STRtree spatial indexing and provenance tagging",
        "Groq Llama 3.3 70B agent that drives the live map through a tool/action protocol",
        "Offline-first PWA: hand-written service worker, cached map tiles, offline write queue",
        "18+ table Postgres schema, 40+ RLS policies, ~35 SECURITY DEFINER RPCs, 25 migrations",
        "46-finding formal pre-deploy security audit - all critical and high issues fixed and live-verified",
      ],
      metrics: [
        { k: "Parcels", v: "11,319" },
        { k: "Python", v: "~9.4K LOC" },
        { k: "RLS policies", v: "40+" },
        { k: "Commits", v: "121 solo" },
      ],
      stack: ["Python", "FastAPI", "Vercel Serverless", "Supabase / PostgreSQL", "GeoPandas", "Shapely", "pyproj", "MapLibre GL JS", "Chart.js", "PWA / Service Workers", "Groq Llama 3.3"],
      url: "https://github.com/GoshtasbSh/Keystone_Project_Survey",
      demoUrl: "https://keystone-project-survey.vercel.app/static/index.html",
      demoLabel: "Open the dashboard",
      note:
        "Risk scores shipped are provisional pending the PI's ratification of the scientific weighting; the engineering is audited and live.",
      featured: true,
    },
    {
      key: "fieldsurvey",
      name: "FieldSurvey",
      tag: "Spatial analytics SaaS",
      category: "Geospatial",
      year: "2026",
      status: "Live - alpha",
      role: "Sole developer",
      summary:
        "A multi-tenant SaaS for spatial and field surveys: teams collect geolocated points through an offline-first mobile PWA, import survey CSVs, and explore the result through a geospatial dashboard backed by a Python spatial-statistics engine.",
      detail: [
        "The architecture is deliberately polyglot: a Next.js 15 / React 19 app orchestrating a Supabase PostgreSQL + PostGIS data layer and two Python services - a serverless geocoding and record-linkage matcher, and a FastAPI spatial-statistics microservice built on PySAL/ESDA, SciPy, NumPy, KDEpy, and ruptures.",
        "Heavy analyses are not computed inline. A cache-through compute layer dispatches each analysis card either to a Postgres RPC or to the Python sidecar; the sidecar wrapper reads a shared cache row first and only recomputes when it is stale, writing results back into the same row so both languages share one source of truth.",
        "The statistics catalog is the substance: global Moran's I and Geary's C, LISA and Local Geary with Benjamini-Hochberg FDR correction, bivariate Moran and Lee's L, Getis-Ord Gi* hot-spot detection, a Kulldorff spatial scan statistic implemented from scratch with a Monte-Carlo permutation p-value, Emerging Hot Spot Analysis with a Mann-Kendall trend test, spatial-lag (2SLS) and spatial-error (FGLS) regression with AIC selection, AAPOR response rates, post-stratification weighting with Kish effective sample size and design effect, FFT-accelerated KDE, PELT change-point detection, and a bootstrap Monte-Carlo finish-date forecaster.",
        "On the geospatial side: a four-tier bipartite record-linkage matcher (exact address, fuzzy street, same parcel, haversine proximity), PostGIS GiST indexes with geography-cast distance and the KNN operator for parcel snapping, and choropleth symbology built from scratch - Fisher-Jenks natural breaks by dynamic programming, quantile, and equal-interval with colorblind-safe palettes.",
      ],
      highlights: [
        "~47,000 LOC across TypeScript, Python, and SQL, delivered solo in 258 commits",
        "19-endpoint FastAPI spatial-statistics engine (PySAL/ESDA, SciPy, KDEpy, ruptures)",
        "Kulldorff spatial scan statistic and Fisher-Jenks classification implemented from scratch",
        "4-tier geocoding + bipartite record-linkage matcher with a one-to-one matching invariant",
        "Offline-first PWA with IndexedDB outbox and exponential-backoff sync (1s to 30m)",
        "47 test files across Vitest, Playwright, and pytest; RLS on every table",
      ],
      metrics: [
        { k: "Code", v: "~47K LOC" },
        { k: "Commits", v: "258 solo" },
        { k: "Analyses", v: "60+ (28+ wired)" },
        { k: "API surface", v: "46 + 19 routes" },
      ],
      stack: ["Next.js 15", "React 19", "TypeScript", "Supabase", "PostGIS", "FastAPI", "PySAL / ESDA", "SciPy", "MapLibre GL", "Playwright", "Vercel"],
      url: "https://github.com/GoshtasbSh/fieldsurvey",
      demoUrl: "https://fieldsurvey-alpha.vercel.app",
      demoLabel: "Open the app",
      note:
        "The catalog defines 60+ analyses; 28+ are wired to a live compute backend. The regression suite is spatial econometrics (spatial-lag 2SLS and spatial-error FGLS), not geographically weighted regression.",
      featured: true,
    },
    {
      key: "cedarkey",
      name: "Cedar Key Bayesian Re-Analysis",
      tag: "Bayesian + causal inference",
      category: "Research",
      year: "2026",
      status: "Live dashboard - MIT licensed",
      role: "Sole developer",
      summary:
        "A rigorous Bayesian and causal-inference re-analysis of a coastal-community infrastructure survey, replacing 195 univariate regressions with a coherent portfolio of seven modern statistical models - deployed as an interactive dashboard.",
      detail: [
        "The seven-model portfolio spans psychometrics, discrete choice, and causal inference: a Bayesian graded-response IRT measurement model over the 15-item New Ecological Paradigm scale; latent class analysis with K chosen by BIC; a joint three-outcome multinomial logit with regularized horseshoe priors and a partial Plackett-Luce top-3 likelihood; a Plackett-Luce rank-ordered logit with the exact likelihood hand-coded in PyTensor; an SEM with mediation and Imai-Keele-Tingley sensitivity analysis; Bayesian Causal Forests for heterogeneous treatment effects; and causal DAG structure learning with edge-stability bootstrapping.",
        "Latent-trait uncertainty is propagated into the downstream causal models with plausible-values multiple imputation (M=30) rather than plugging in point estimates - the methodological detail that makes the portfolio coherent rather than a pile of separate models.",
        "A pre-publication forensic audit (24 findings, all fixed and re-verified) caught two real problems: a NEP sign-flip bug, and a circular-inference flaw where a joint model was recovering its own coefficients at r = 0.96. The fix was architectural - split into a measurement-only model feeding downstream estimators.",
        "The pipeline is orchestrated end to end: dependency-ordered model runs, MD5 data-hash provenance stamped into every posterior for staleness detection, ~12 GB of NetCDF posteriors under management, a synthetic PII-free data generator sampled from the posterior so the whole thing is reproducible without restricted human-subjects data, and a Streamlit dashboard with live model re-fitting, Dockerized for Hugging Face Spaces.",
      ],
      highlights: [
        "Seven-model portfolio: IRT, LCA, horseshoe multinomial logit, Plackett-Luce, SEM mediation, BART causal forests, DAG discovery",
        "Plausible-values multiple imputation (M=30) propagating latent-trait uncertainty downstream",
        "Diagnosed and corrected a circular-inference flaw (r = 0.96 self-recovery) by re-architecting the measurement model",
        "~12 GB of NetCDF posteriors with hash-based provenance and staleness detection",
        "71 automated tests plus two formal audits (19-finding review, 24-finding pre-publication audit)",
        "Full convergence diagnostics throughout: R-hat, ESS, divergences, energy plots, posterior predictive checks",
      ],
      metrics: [
        { k: "Python", v: "~19.7K LOC" },
        { k: "Models", v: "7" },
        { k: "Tests", v: "71" },
        { k: "Posteriors", v: "~12 GB" },
      ],
      stack: ["Python", "PyMC 5", "ArviZ", "pymc-bart", "stepmix", "semopy", "pgmpy", "causal-learn", "Streamlit", "Plotly", "Docker"],
      url: null,
      demoUrl: "https://huggingface.co/spaces/Goshtasb/cedar-key-nep",
      demoLabel: "Open the dashboard",
      note:
        "This is place-based ranking analysis of a coastal community, not GIS: the 'places' are ranked categories, not coordinates.",
      featured: true,
    },
    {
      key: "proxima",
      name: "Proxima",
      tag: "CP-SAT scheduling optimizer",
      category: "Full-stack",
      year: "2026",
      status: "Prototype - web pilot ready",
      role: "Sole developer",
      summary:
        "A construction workforce-management platform whose core is an AI-assisted crew-scheduling optimizer: Google OR-Tools CP-SAT decides which worker does which task on which day across every active jobsite, with LLMs at the edges parsing field notes and explaining decisions.",
      detail: [
        "The optimizer models scheduling as generalized resource-constrained project scheduling (RCPSP / MS-RCPSP / RCPSP-max) in coupled CP-SAT layers: an interval and cumulative layer deciding when each activity runs, and an assignment layer deciding which worker performs it. It handles all four precedence link types with integer lags, renewable resources by skill, delivery-gated materials as reservoir constraints, per-worker calendars, and a normalized multi-objective where every term is scaled before its weight is applied so the priority hierarchy is mathematically real.",
        "It was validated against academic benchmark libraries - PSPLIB, iMOPSE MS-RCPSP, and RCPSP/max - reproducing published optima at 0% gap on the PSPLIB j30 instances, with an independent adversarial 'truth oracle' that re-checks every solution from scratch to prove the model is not silently accepting invalid schedules.",
        "The distinctive piece is encoding construction safety standards as hard solver constraints: ACI 305R-20 hot-weather concreting (via a pre-computed Menzel evaporation-rate model) and OSHA 1926 fall protection gate whether a task can be scheduled at all on a given forecast day. A Clarke-Wright savings term batches a worker's nearby projects onto the same day, and a separate 2-opt route optimizer minimizes intra-day travel.",
        "LLMs sit strictly at the edges: an eight-provider abstraction extracts free-text field notes into schema-constrained solver constraints (prompt-injection hardened, human-approval gated) and generates standard-cited counterfactual explanations. The LLM layer can never raise into the solver - every AI path falls back to a deterministic template.",
      ],
      highlights: [
        "OR-Tools CP-SAT optimizer validated against PSPLIB / iMOPSE / RCPSP-max at 0% gap",
        "Construction safety standards (ACI 305R-20, OSHA 1926) encoded as hard solver constraints",
        "8-provider LLM abstraction with deterministic fallbacks and human-in-the-loop approval gates",
        "React Native + Expo app running on iOS, Android, and web from one codebase",
        "~90-table multi-tenant Postgres schema across 87 migrations with row-level-security isolation",
        "~896 passing backend tests including per-constraint RED/GREEN binding tests and tenant-isolation security tests",
      ],
      metrics: [
        { k: "DB tables", v: "~90" },
        { k: "Migrations", v: "87" },
        { k: "Backend tests", v: "~896" },
        { k: "Platforms", v: "iOS / Android / web" },
      ],
      stack: ["Python 3.13", "FastAPI", "OR-Tools CP-SAT", "React Native / Expo", "TypeScript", "Supabase / PostgreSQL", "Deno Edge Functions", "H3", "Cloud Run", "Docker"],
      url: null,
      demoUrl: null,
      note:
        "Advanced construction-realism constraints are code-complete and unit-tested but dormant in production until a tenant populates the relevant config tables. Solo-built prototype, not a shipped commercial product.",
      featured: true,
    },
    {
      key: "petrotech",
      name: "PetroTech Connect",
      tag: "B2B marketplace platform",
      category: "Full-stack",
      year: "2026",
      status: "Prototype - pilot deployed",
      role: "Sole developer",
      summary:
        "A self-hostable B2B marketplace and price-intelligence platform for the petroleum-to-textile supply chain: a lead-matching and ranking engine, a double-entry wallet ledger with pluggable payment gateways, a real-time SSE layer, and an external commodity-price ETL microservice.",
      detail: [
        "The codebase is a feature-sliced modular monolith - organized by business capability, with server-only boundaries physically preventing money, lead-distribution, and auth logic from being bundled into the client, and a central typed authorization policy engine applied uniformly across features.",
        "The matching engine is a pure, unit-tested function that decides which sellers receive a buyer's request: an eligibility filter, then whitelist-first, rating-descending, recency, and a randomized tie-break among fully equal-rank candidates so a hard recipient cap does not permanently starve new or unrated sellers. It feeds off a reputation-scoring model that aggregates ratings, response time, completion, on-time delivery, and dispute rates from transactional data.",
        "The wallet subsystem is written like fintech code: integer money throughout, a running-balance transaction ledger with a database-level non-negative CHECK constraint, idempotency keys on charges, and gateway-reference uniqueness so a payment callback cannot be replayed across two top-ups.",
        "A standalone Dockerized ETL microservice pulls commodity and FX series from Alpha Vantage, FRED, and EIA on a daily cron with retry-with-backoff and day-level caching, normalizes heterogeneous source series into canonical price points, and loads them idempotently through an authenticated internal endpoint. It is deliberately never bundled into the main app image - a data-locality constraint designed around.",
      ],
      highlights: [
        "~125K LOC across 516 source files; 40+ Prisma models; ~60 App Router routes",
        "Fairness-aware ranking engine with randomized tie-break and a reputation-scoring model",
        "Double-entry wallet with idempotency keys, replay-safe callbacks, and integer-money discipline",
        "Advanced Postgres: JSONB GIN indexes, partial indexes, NULLS NOT DISTINCT uniques, CHECK constraints",
        "Full internationalization (English + Persian with RTL), multi-theme system, installable PWA",
        "~560 Vitest tests + 24 Playwright E2E journeys; multi-phase security audit closing a P0 auth bypass",
      ],
      metrics: [
        { k: "Code", v: "~125K LOC" },
        { k: "DB models", v: "40+" },
        { k: "Tests", v: "~560 + 24 E2E" },
        { k: "Migrations", v: "13 zero-drift" },
      ],
      stack: ["TypeScript", "Next.js 15", "React 19", "PostgreSQL", "Prisma 7", "Auth.js v5", "Zod", "next-intl", "Docker / Caddy", "Vitest", "Playwright"],
      url: null,
      demoUrl: null,
      note:
        "Solo-built. The matching and scoring logic is heuristic and statistical, not machine-learned. Final readiness verdict was GO with deployment and operations caveats.",
      featured: false,
    },
    {
      key: "jobfinder",
      name: "JobFinder",
      tag: "Local-first LLM automation",
      category: "AI / LLM",
      year: "2026",
      status: "Running locally",
      role: "Sole developer",
      summary:
        "A local-first job-search automation platform: deterministic Python scrapers ingest postings from official free sources into SQLite, an LLM orchestration engine scores each posting against a CV and drafts tailored application documents, and a Next.js dashboard is the human control surface.",
      detail: [
        "Discovery uses no LLM at all - that is a cost decision. Pluggable source modules behind a common fetch() contract pull from company ATS REST APIs (Greenhouse, Lever, Ashby, SmartRecruiters, Recruitee, Workable), the federal USAJobs API, academic RSS feeds, read-only Gmail OAuth for job-alert emails, aggregator APIs, and MCP tools - each with per-source fault isolation so one failure never aborts a run.",
        "Deduplication is a URL-canonicalizing key with idempotent ON CONFLICT upserts that never overwrite good data with nulls - and the same key is reimplemented in TypeScript so browser-captured jobs collide correctly with pipeline-ingested ones.",
        "The LLM layer routes each pipeline task independently to a provider and model resolved at call time from a three-tier fallback, with a cheap tier for scoring and a quality tier for drafting. Structured output is enforced without brittle schema flags: in-prompt schema-by-example, low-temperature JSON mode, and a loose-parse/repair layer, with canonical JSON Schemas kept as the contract of record.",
        "Three hard rules are enforced in code rather than in prose: never auto-submit, never invent facts (a pause/ask loop turns any missing fact into a user-facing question instead of a hallucination, backed by validators and an anti-hollow-completion guard), and never incur metered charges (the API key is physically removed from the child process environment so the CLI cannot fall back to billed usage).",
      ],
      highlights: [
        "Multi-source ingestion across REST APIs, RSS, OAuth email, and MCP tools with per-source fault isolation",
        "Multi-provider, per-task LLM routing with cost-tiered model selection, live-editable without restart",
        "Hallucination-resistant document generation via a pause/ask loop surfaced in the UI",
        "Crash-recoverable task queue with atomic claiming and stale-task reaping, scheduled by macOS launchd",
        "SSRF hardening, path-traversal confinement, and out-of-repo secrets with write-only UI handling",
        "Fixture-based offline parser tests (pytest + Vitest) pinning every source's canonical output shape",
      ],
      metrics: [
        { k: "Languages", v: "Python + TS" },
        { k: "Sources", v: "10+ ingest paths" },
        { k: "LLM providers", v: "5" },
        { k: "Scheduling", v: "launchd, 3 agents" },
      ],
      stack: ["Python 3.11", "SQLite (WAL)", "Next.js 16", "React 19", "TypeScript", "Claude Code (headless)", "MCP", "LaTeX", "pytest", "Vitest"],
      url: null,
      demoUrl: null,
      note: "Personal single-user tool running on my own machine, by design - not a hosted service.",
      featured: false,
    },
    {
      key: "neico",
      name: "NeiCo",
      tag: "iOS + Django marketplace",
      category: "Full-stack",
      year: "2025",
      status: "Prototype",
      role: "Sole developer",
      summary:
        "A hyperlocal neighbor-to-neighbor grocery-coordination platform: a native SwiftUI iOS app with MapKit spatial features on an MVVM architecture, backed by a Django REST Framework API with JWT auth and a 19-endpoint surface across 8 domain apps.",
      detail: [
        "The iOS client is pure Apple first-party frameworks with zero third-party dependencies: SwiftUI with UIKit interop, Combine, async/await, MapKit and CoreLocation, PhotosUI. Notable engineering includes a hand-built draggable pull-up bottom sheet, dual map implementations (SwiftUI Map and a UIViewRepresentable MKMapView path), a Combine location pipeline that centers the map on live position, distance-based sorting of nearby orders, and JWT auth with NotificationCenter-driven auto-logout.",
        "The backend models the core mechanic directly: the grocery-list viewset deliberately excludes the requester's own lists so the feed surfaces neighbors' lists to fulfill, and accepting an order mints reward points in a single transactional action.",
        "The project also carried a structured product and market validation - market sizing, unit-economics modeling, regulatory and payments analysis (money-transmitter law, food safety, gig-labor classification), and a competitor teardown - which concluded the as-pitched consumer app was not fundable and identified a defensible B2B pivot worth testing. Documenting that honestly was the point of the exercise.",
      ],
      highlights: [
        "Native SwiftUI app with MVVM, Combine, async/await and zero third-party dependencies",
        "MapKit / CoreLocation spatial features: live-location centering, custom annotations, distance sorting",
        "Django REST Framework backend: custom email-login user model, SimpleJWT, 19 endpoints, 8 apps",
        "ETL management commands and fixture generation seeding stores and catalogs from JSON",
        "Structured market validation: unit economics, regulatory analysis, competitor teardown",
      ],
      metrics: [
        { k: "Platforms", v: "iOS + REST API" },
        { k: "Endpoints", v: "19" },
        { k: "Django apps", v: "8" },
        { k: "Dependencies", v: "0 third-party (iOS)" },
      ],
      stack: ["Swift 5", "SwiftUI", "Combine", "MapKit", "CoreLocation", "Python", "Django 4.2", "Django REST Framework", "PostgreSQL", "SimpleJWT"],
      url: null,
      demoUrl: null,
      note: "Functional solo-built prototype with dev-only security posture; not deployed. No ML in this codebase.",
      featured: false,
    },
    {
      key: "disasters-game",
      name: "Disasters: Through the Looking Glass",
      tag: "3D multiplayer web game",
      category: "Full-stack",
      year: "2026",
      status: "Playable - deployed",
      role: "Primary developer",
      summary:
        "A cooperative educational board game about how disasters expose social inequality, built as both a 3D real-time multiplayer web app and a press-ready physical game generated from the same source data.",
      detail: [
        "The engine is a pure, seed-deterministic state machine (~4,500 LOC) fully decoupled from UI and transport: every rule is a pure (GameState, action) to GameState function, and all randomness derives from one seed - which is what makes cheap last-write-wins multiplayer provably correct, because independent clients replaying the same actions converge to identical state.",
        "The board is a hand-written Three.js scene (~1,000 LOC, deliberately raw rather than react-three-fiber) with procedural PBR materials, image-based lighting, legal-move highlighting, click-picking, and four camera presets including a mobile top-down view.",
        "Multiplayer runs on a PartyKit authoritative server with host/joiner role negotiation from the first message, session-based identity recovery on refresh, echo suppression, and a single-writer 'AI authority' pattern so only one client drives the heuristic AI opponents - a clean solution to a real distributed-consistency problem.",
        "The physical game is generated programmatically: Node ESM scripts drive headless Chromium through Playwright to render ~20 press-ready PDFs (board, five card decks, envelope and holder dielines, rules cards). The 88-card dataset is a single source of truth for both the app and the print files, so the digital and physical games are provably the same game.",
      ],
      highlights: [
        "Pure seed-deterministic game engine enabling correct last-write-wins multiplayer",
        "Hand-written ~1,000-line Three.js scene with PBR materials and interactive picking",
        "PartyKit authoritative-server multiplayer with reconnection and AI-authority consistency",
        "Rule-based AI opponents using utility-scoring move selection and per-role trade policies",
        "Playwright-driven HTML to PDF print pipeline producing ~20 press-ready files",
        "~62 Vitest unit tests plus Playwright E2E; installable PWA with offline shell",
      ],
      metrics: [
        { k: "TypeScript", v: "~9K LOC" },
        { k: "Tests", v: "~62" },
        { k: "Cards", v: "88 across 5 decks" },
        { k: "Print PDFs", v: "~20 generated" },
      ],
      stack: ["TypeScript", "Next.js 14", "React 18", "Three.js", "Zustand", "PartyKit / WebSockets", "Framer Motion", "jsPDF", "Playwright", "Vercel"],
      url: null,
      demoUrl: null,
      note: "The AI opponents are rule-based heuristic agents, not machine learning.",
      featured: false,
    },
    {
      key: "dtsc-web",
      name: "DTSC Lab Website & Lab Book",
      tag: "Framework-free front end",
      category: "Full-stack",
      year: "2026",
      status: "Prototype - client deliverable",
      role: "Sole developer and designer",
      summary:
        "A complete academic lab web presence built entirely framework-free - a routed SPA-style site with an interactive 3D-flipbook Lab Book, plus a nine-page interactive review microsite delivered to a stakeholder board with QA documentation.",
      detail: [
        "Every file is a self-contained HTML document with hand-rolled CSS and vanilla JavaScript, deliberately designed to be portable into WordPress without new plugins. The site runs on a custom client-side hash router with 10 routes, browser back/forward support, dynamic document titles, ARIA active-state management, and nested sub-page tab navigation for per-project mini-sites.",
        "The interaction work is the interesting part: IntersectionObserver scroll reveals, an accessible auto-playing carousel that pauses on hover and focus, a reading-progress bar, a scrollspy table of contents, a 3D CSS flipbook with perspective page turns driven by keyboard, click zones, and thumbnails, and a scrollytelling progress rail - every animated component gated behind prefers-reduced-motion with a graceful fallback.",
        "Process rigor: six full-site iterations from a written, dated, approved design specification, nine structured A/B design variants (six navigation concepts, three project-page layouts), and three competing Lab Book interaction prototypes synthesized into one production page.",
      ],
      highlights: [
        "~11,800 lines of HTML/CSS/vanilla JS across 19 self-contained files, zero frameworks",
        "Custom hash-based SPA router with history support and nested mini-site navigation",
        "3D CSS flipbook with keyboard, click-zone, and thumbnail controls",
        "Accessibility throughout: ARIA state, :focus-visible, keyboard support, reduced-motion fallbacks",
        "Client deliverable packaged with a QA report and a content-readiness checklist",
      ],
      metrics: [
        { k: "Code", v: "~11.8K lines" },
        { k: "Files", v: "19 self-contained" },
        { k: "Iterations", v: "6 full-site" },
        { k: "A/B variants", v: "9" },
      ],
      stack: ["HTML5", "CSS3", "Vanilla JavaScript", "IntersectionObserver", "CSS 3D transforms", "Constraint Validation API"],
      url: null,
      demoUrl: null,
      note: "High-fidelity prototypes plus one delivered client review package; the WordPress production build is the implementation target.",
      featured: false,
    },
    {
      key: "video-trimmer",
      name: "Video & Transcript Trimmer",
      tag: "Media tooling",
      category: "Full-stack",
      year: "2025",
      status: "Open source",
      role: "Sole developer",
      summary:
        "A Streamlit app that trims or cuts video files while keeping the accompanying WebVTT transcript perfectly time-synchronized - captions that straddle a cut boundary are clipped and every surviving caption is remapped onto the shortened timeline.",
      detail: [
        "Two algorithms carry the app. Cut mode computes the interval complement: given a set of segments to remove, it walks the sorted cut intervals and emits the gaps between them, correctly handling overlapping cuts through a running end pointer. Transcript re-timing then skips captions outside each kept segment, clips partially-overlapping ones, and remaps the survivors into the new timeline by subtracting the segment start and adding the cumulative output offset.",
        "Video processing runs through MoviePy/FFmpeg (sub-clip extraction, concatenation, H.264/AAC re-encoding) with tempfile-based handling for uploads and outputs, and Streamlit session state so results persist across reruns and stay downloadable.",
      ],
      highlights: [
        "Interval-complement algorithm deriving kept segments in cut mode",
        "WebVTT caption re-timing with boundary clipping and cumulative-offset remapping",
        "Flexible timestamp parser supporting MM:SS and HH:MM:SS with fractional seconds",
      ],
      metrics: [
        { k: "Language", v: "Python" },
        { k: "Scope", v: "Single-file app" },
      ],
      stack: ["Python", "Streamlit", "MoviePy", "FFmpeg", "webvtt-py"],
      url: "https://github.com/GoshtasbSh/video-transcript-editor",
      demoUrl: null,
      note: "A focused utility, not a large system. It edits an existing .vtt transcript; it does not generate one.",
      featured: false,
    },
    {
      key: "cifar-transfer",
      name: "Built-Environment Feature Detection",
      tag: "Transfer learning",
      category: "ML / CV",
      year: "2024",
      status: "Course capstone",
      role: "Sole developer",
      summary:
        "Optimizing built-environment feature detection using transfer learning on CIFAR-100. Pattern Recognition capstone, Fall 2024.",
      detail: [
        "A transfer-learning study applying pretrained convolutional backbones to built-environment feature detection, evaluating how far generic visual representations carry into an urban-imagery task.",
      ],
      highlights: [],
      metrics: [],
      stack: ["PyTorch", "Transfer Learning", "CIFAR-100"],
      url: "https://github.com/GoshtasbSh",
      demoUrl: null,
      featured: false,
    },
    {
      key: "flowers-unet",
      name: "Flower Classification + Lung X-ray Segmentation",
      tag: "Deep learning",
      category: "ML / CV",
      year: "2024",
      status: "Open source",
      role: "Sole developer",
      summary:
        "Transfer-learning flower classification with MobileNetV2 and Xception, plus U-Net segmentation of lung X-rays. Applied Machine Learning, Spring 2024.",
      detail: [
        "Two paired tasks: a classification track comparing pretrained MobileNetV2 and Xception backbones under fine-tuning, and a segmentation track training a U-Net on chest radiographs with standard overlap metrics.",
      ],
      highlights: [],
      metrics: [],
      stack: ["TensorFlow", "U-Net", "MobileNetV2", "Xception"],
      url: "https://github.com/GoshtasbSh/deep-learning-image-classification-and-segmentation",
      demoUrl: null,
      featured: false,
    },
    {
      key: "yolo-math",
      name: "Handwritten Math Symbols (YOLOv5)",
      tag: "Object detection",
      category: "ML / CV",
      year: "2022",
      status: "Open source",
      role: "Sole developer",
      summary:
        "YOLOv5 classification and object detection over 10 classes of handwritten mathematical symbols. Graduate ML project, Fall 2022.",
      detail: [
        "An end-to-end detection pipeline: dataset preparation and annotation, YOLOv5 training, and evaluation of both the classification and localization tracks.",
      ],
      highlights: [],
      metrics: [],
      stack: ["YOLOv5", "PyTorch"],
      url: "https://github.com/GoshtasbSh/handwritten-math-symbol-recognition-yolov5",
      demoUrl: null,
      featured: false,
    },
    {
      key: "nn-experiments",
      name: "Neural Network Architecture Experiments",
      tag: "Neural networks",
      category: "ML / CV",
      year: "2026",
      status: "Open source",
      role: "Sole developer",
      summary:
        "MLP regression on California Housing plus a systematic architecture study on canonical 2D classification problems - depth, width, and activation choices against decision-boundary behavior.",
      detail: [],
      highlights: [],
      metrics: [],
      stack: ["PyTorch", "scikit-learn", "NumPy"],
      url: "https://github.com/GoshtasbSh/neural-network-classification-experiments",
      demoUrl: null,
      featured: false,
    },
    {
      key: "retail-ml",
      name: "Retail Sales Prediction & Classification",
      tag: "ML pipeline",
      category: "ML / CV",
      year: "2026",
      status: "Open source",
      role: "Sole developer",
      summary:
        "An end-to-end ML pipeline on supermarket sales data: regression for gross income and unit price, classification for customer type, gender, and weekday.",
      detail: [],
      highlights: [],
      metrics: [],
      stack: ["scikit-learn", "pandas"],
      url: "https://github.com/GoshtasbSh/retail-sales-prediction-and-classification",
      demoUrl: null,
      featured: false,
    },
    {
      key: "pca-study",
      name: "PCA Impact on Classification",
      tag: "Empirical study",
      category: "ML / CV",
      year: "2026",
      status: "Open source",
      role: "Sole developer",
      summary:
        "An empirical study of PCA's effect on accuracy and training time for Logistic Regression versus Random Forest on a ship image dataset.",
      detail: [],
      highlights: [],
      metrics: [],
      stack: ["scikit-learn", "NumPy"],
      url: "https://github.com/GoshtasbSh/dimensionality-reduction-impact-on-classification",
      demoUrl: null,
      featured: false,
    },
    {
      key: "landfill-ga",
      name: "Landfill Site Selection (Genetic Algorithm)",
      tag: "Spatial optimization",
      category: "Geospatial",
      year: "2017",
      status: "Academic project",
      role: "Sole developer",
      summary:
        "Site selection of a landfill using genetic algorithms over multi-criteria GIS layers.",
      detail: [],
      highlights: [],
      metrics: [],
      stack: ["MATLAB", "Genetic Algorithms", "GIS"],
      url: null,
      demoUrl: null,
      featured: false,
    },
    {
      key: "hospital-mcdm",
      name: "Hospital Site Selection (MCDM + GIS)",
      tag: "Decision analysis",
      category: "Geospatial",
      year: "2014",
      status: "Academic project",
      role: "Sole developer",
      summary:
        "Site selection of urban hospitals using a combined multi-criteria decision-making and GIS spatial-analysis workflow.",
      detail: [],
      highlights: [],
      metrics: [],
      stack: ["ArcGIS", "AHP", "MCDM"],
      url: null,
      demoUrl: null,
      featured: false,
    },
  ],

  publications: [
    {
      year: 2024,
      authors:
        "N. Soltani Nejad, R. Rastegar, G. Shahriari Mehr, F. Taheri Azad",
      title:
        "Conceptualizing the Tourist Journey: Qualitative Analysis of Tourist Experiences on TripAdvisor",
      venue: "Journal of Quality Assurance in Hospitality and Tourism",
      doi: "https://doi.org/10.1080/17489725.2021.1880029",
      pdfUrl: null,
      openAccess: false,
      tags: ["Qualitative", "Tourism", "Text Analysis"],
    },
    {
      year: 2021,
      authors:
        "G. Shahriari Mehr, M. Delavar, C. Claramunt, B. N. Araabi, M. R. A. Dehaqani",
      title:
        "A Store Location-based Recommender System Based on User's Position and Web Searches",
      venue: "Journal of Location Based Services",
      doi: "https://doi.org/10.1080/17489725.2021.1880029",
      pdfUrl: "assets/paper-2021-lbs-recommender.pdf",
      openAccess: true,
      tags: ["LBS", "Recommender", "First Author"],
    },
    {
      year: 2020,
      authors:
        "G. Shahriari Mehr, M. Delavar, C. Claramunt, B. N. Araabi, M. R. A. Dehaqani",
      title:
        "Discover Points of Interest based on Users' Internet Searches Through an Online Shopping Website",
      venue: "ISPRS International Joint Conference 2019",
      doi: "#",
      pdfUrl: "assets/paper-2020-isprs-poi.pdf",
      openAccess: true,
      tags: ["POI", "Recommender", "Conference"],
    },
  ],

  teaching: [
    { course: "Shelter Development", school: "University of Florida", terms: "Summer 2024 - Fall 2024 - Summer 2025 - Fall 2025" },
    { course: "Introduction to Planning Information Systems", school: "University of Florida", terms: "Fall 2023 - Spring 2025" },
    { course: "Introduction to Urban Analytics", school: "University of Florida", terms: "Fall 2023" },
    { course: "Geographic Information Systems I", school: "University of Tehran", terms: "Spring 2018" },
  ],

  honors: [
    "Graduate Support Funding, Office of the Provost, University of Florida (2021)",
    "Ranked 10th of 2,000 in Iran's national graduate entrance exam (1st at K. N. Toosi University, 2016)",
    "Ranked in the top 1% of ~300,000 in Iran's national university entrance exam (2012)",
  ],

  skills: {
    Languages: ["Python", "TypeScript", "JavaScript", "SQL", "Swift", "C#", "MATLAB", "Bash"],
    "AI / LLM": ["LLM agents", "Tool calling", "RAG", "LangGraph", "pgvector", "LiteLLM", "Prompt engineering", "Prompt-injection defense", "LLM evaluation harnesses", "MCP"],
    "ML / Statistics": ["PyTorch", "TensorFlow", "scikit-learn", "PyMC", "ArviZ", "BART / causal forests", "IRT", "SALib (Sobol)", "U-Net", "YOLOv5"],
    "Geo / Spatial": ["PostGIS", "GeoPandas", "Shapely", "pyproj", "DuckDB spatial", "PySAL / ESDA", "Mesa-Geo", "MapLibre GL", "deck.gl", "ArcGIS Pro", "QGIS"],
    "Backend / Data": ["FastAPI", "Django", "SQLAlchemy", "PostgreSQL", "Supabase", "Redis / arq", "Prisma", "SQLite", "ETL pipelines"],
    "Frontend / Apps": ["Next.js", "React 19", "Lit / Web Components", "Tailwind", "React Native / Expo", "SwiftUI", "Three.js", "PWA / service workers"],
    "Infra / Quality": ["Docker", "Vercel", "Hugging Face Spaces", "GitHub Actions", "pytest", "Vitest", "Playwright", "Security auditing"],
  },

  // ------------ Detailed records (modal pop-ups) ------------
  degreesDetailed: [
    {
      key: "phd",
      degree: "PhD",
      field: "Design, Construction & Planning",
      school: "University of Florida",
      city: "Gainesville, FL",
      years: "Jan 2022 - 2026",
      status: "Defended in 2026",
      gpa: null,
      advisor: "Dr. Jason Von Meding",
      thesis:
        "Evaluating Different Scenarios for Food Access in Jacksonville Health Zone 1 using Agent-Based Modeling.",
      blurb:
        "Population-scale agent-based simulation of how residents reach food under different policy interventions, calibrated against real census and survey targets and evaluated with Sobol sensitivity analysis and 50-seed Monte Carlo replication. The dissertation delivers concrete policy recommendations on transit, retail siting, and pricing - all derived from the ABM results. A generative twin re-runs the same world with LLM-driven household decisions.",
      highlights: [
        "Spatial ABM over 45 real census tracts in Jacksonville Health Zone 1 (~48,000 households)",
        "Calibrated discrete-choice utility model (calibration error 0.095) on census, BLS, and DCF data",
        "Sobol global sensitivity analysis and 50-seed Monte Carlo with bootstrap CIs and effect sizes",
        "Generative ABM extension: LLM household agents with episodic and word-of-mouth RAG memory",
        "Policy recommendations from simulation results across four interventions",
      ],
    },
    {
      key: "msc-ece",
      degree: "MSc",
      field: "Electrical & Computer Engineering",
      school: "University of Florida",
      city: "Gainesville, FL",
      years: "Aug 2023 - Dec 2025",
      status: "Conferred December 2025",
      gpa: "3.81 / 4.00",
      advisor: null,
      thesis: null,
      certificateUrl: "assets/msc-ece-degree.pdf",
      blurb:
        "Dual degree pursued alongside the PhD to bring modern machine learning, computer vision, and LLM / agent-AI methods into the urban-analytics work. Capstones spanned pattern recognition, deep learning, and applied ML; the LLM line that followed became GeoChatBot, Local Glean, and the generative ABM.",
      highlights: [
        "Pattern Recognition - CIFAR-100 transfer learning for built-environment features (Fall 2024)",
        "Applied ML - flower classification (MobileNetV2 / Xception) + U-Net lung X-ray segmentation (Spring 2024)",
        "Neural Networks & Deep Learning - CNN + MLP on Kuzushiji-MNIST (Fall 2023)",
        "Agent AI + LLM line - GeoChatBot and Local Glean, both live (2026)",
        "UF Machine Learning Certificate (ECE Department, Jan 2023 - Dec 2024)",
        "Coursera Machine Learning + Deep Learning Specialization (2020)",
      ],
    },
    {
      key: "msc-gis",
      degree: "MSc",
      field: "Geographic Information Science",
      school: "University of Tehran",
      city: "Tehran, Iran",
      years: "Sep 2016 - Aug 2019",
      status: "Conferred - Thesis grade: Excellent",
      gpa: null,
      advisor: "Profs. M. Delavar, C. Claramunt, B. Nadjar Araabi, M. R. Abolghasemi",
      thesis:
        "Developing a Location-Based Recommender System using Pattern Recognition with Users' Points of Interest and Internet Behavior.",
      blurb:
        "Trained as a GIS scientist with a research focus on location-based services and recommender systems. Two peer-reviewed papers published from this thesis.",
      highlights: [
        "Thesis grade: Excellent",
        "Ranked 10th of ~2,000 in Iran's national graduate entrance exam (1st at K. N. Toosi)",
        "Two peer-reviewed papers from this thesis",
        "TA - GIS I (Spring 2018)",
      ],
    },
    {
      key: "bsc",
      degree: "BSc",
      field: "Civil-Geomatics Engineering",
      school: "K. N. Toosi University of Technology",
      city: "Tehran, Iran",
      years: "Sep 2012 - Aug 2016",
      status: "Conferred",
      gpa: "16.07 / 20",
      advisor: null,
      thesis: "Evaluation of Methods for 3D Cadaster.",
      blurb:
        "Classical civil-geomatics - surveying, photogrammetry, GIS, CAD. The discipline that taught me to care about error budgets and coordinate systems before anything else.",
      highlights: [
        "Ranked in the top 1% of ~300,000 in Iran's national university entrance exam (2012)",
        "Site-selection projects using GIS + AHP and Genetic Algorithms",
      ],
    },
  ],

  affiliationsDetailed: [
    {
      key: "fiber",
      name: "FIBER",
      full: "Florida Institute for Built Environment Resilience",
      school: "University of Florida",
      role: "Graduate Research Assistant",
      years: "Jan 2022 - Present",
      link: "https://dcp.ufl.edu/fiber/",
      advisor: null,
      project: null,
      blurb:
        "Long-running GRA appointment at FIBER - the Florida Institute for Built Environment Resilience.",
    },
    {
      key: "dtsc",
      name: "DTSC Lab",
      full: "Disasters, Trust, and Social Change Lab",
      school: "University of Florida",
      role: "Graduate Research Assistant",
      years: "Jun 2023 - Present",
      link: "https://dcp.ufl.edu/fiber/disasters-trust-and-social-change-lab/",
      advisor: null,
      project: null,
      blurb:
        "GRA at the DTSC Lab, where most of my applied engineering work lives: the KeyStone Heights research platform (field PWA + GIS analytics dashboard, in production), the Cedar Key Bayesian re-analysis and its deployed dashboard, Local Glean (the lab's FERPA-safe AI assistant), and the lab's web presence and Lab Book.",
    },
    {
      key: "iadapt",
      name: "iAdapt",
      full: "International Center for Adaptation Planning & Design",
      school: "University of Florida",
      role: "Graduate Research Assistant",
      years: "Aug 2025 - Feb 2026",
      status: "Completed",
      link: "https://dcp.ufl.edu/iadapt",
      advisor: "Dr. Zhong-Ren Peng",
      project: "FDOT District 5 - review and comparative analysis of existing transport analyses for Central Florida.",
      blurb:
        "Completed appointment (Aug 2025 - Feb 2026) on the FDOT District 5 project at iAdapt, focused on review and comparative analysis of existing transport analyses for Central Florida.",
    },
  ],

  axisDetails: {
    "Agent AI and LLMs": {
      one: "Production LLM agents: planning, tool calling, RAG, and verification.",
      stack: ["LLM agents", "LangGraph", "RAG", "Tool calling", "pgvector", "LiteLLM", "TypeScript", "Python"],
      items: [
        { year: "2026", what: "GeoChatBot - browser-native plan-then-execute agent over 28 typed tools, hybrid RAG (MiniLM + BM25 + RRF), 5 LLM providers, claim-grounding verifier. Live." },
        { year: "2026", what: "Local Glean - 9-node LangGraph pipeline with Postgres checkpointing, SSE streaming, and a fail-closed anti-hallucination verifier on an on-premise gateway. Live." },
        { year: "2026", what: "Generative ABM - LLM household agents with two-tier RAG memory (episodic + word-of-mouth over a spatial kNN graph), made reproducible with temperature-0, fixed seeds, and content-addressed prompt caching." },
        { year: "2026", what: "KeyStone LLM analyst - Llama 3.3 70B agent that drives a live map through a tool/action protocol with a deterministic fallback." },
        { year: "2026", what: "JobFinder - multi-provider per-task LLM routing with cost-tiered model selection and a pause/ask loop that refuses to invent facts." },
      ],
    },
    "Agent-Based Modeling": {
      one: "Population-scale simulation of urban behavior in Python.",
      stack: ["Python", "Mesa-Geo", "GeoPandas", "Shapely", "SALib", "sentence-transformers"],
      items: [
        { year: "2022 - 2026", what: "PhD dissertation - food-access ABM in Jacksonville Health Zone 1, defended 2026. ~48,000 households, four policy interventions, calibration error 0.095." },
        { year: "2026", what: "Generative twin of the same model, where each household's choice is made by an LLM - validated byte-for-byte against the rule-based reference." },
        { year: "2026", what: "Sobol global sensitivity analysis, 50-seed Monte Carlo replication, matched-seed counterfactual policy evaluation." },
      ],
    },
    "Machine Learning": {
      one: "Certified and project-based ML across urban, image, and tabular data.",
      stack: ["PyTorch", "TensorFlow", "scikit-learn", "Coursera ML", "UF ML Cert"],
      items: [
        { year: "Dec 2025", what: "MSc in ECE conferred by UF (dual degree alongside the PhD) - GPA 3.81." },
        { year: "Jan 2023 - Dec 2024", what: "UF Machine Learning Certificate (Department of ECE)." },
        { year: "2020", what: "Coursera Machine Learning + Deep Learning Specialization." },
        { year: "Fall 2024", what: "Pattern Recognition capstone - CIFAR-100 transfer learning for built-environment feature detection." },
        { year: "2026", what: "Neural-network architecture experiments; PCA impact study; end-to-end retail sales prediction pipeline." },
      ],
    },
    "Bayesian & Causal Inference": {
      one: "Bayesian modeling, causal inference, and honest uncertainty.",
      stack: ["PyMC", "ArviZ", "pymc-bart", "semopy", "pgmpy", "causal-learn", "stepmix"],
      items: [
        { year: "2026", what: "Cedar Key - seven-model Bayesian and causal portfolio: graded-response IRT, latent class analysis, horseshoe multinomial logit, Plackett-Luce ranking, SEM mediation, Bayesian causal forests, DAG structure learning." },
        { year: "2026", what: "Plausible-values multiple imputation (M=30) propagating latent-trait uncertainty into downstream causal models." },
        { year: "2026", what: "Diagnosed and corrected a circular-inference flaw (r = 0.96 self-recovery) in a joint model by re-architecting to measurement-only." },
        { year: "2026", what: "FieldSurvey - spatial autocorrelation and hot-spot inference with permutation tests and Benjamini-Hochberg FDR correction." },
      ],
    },
    "Spatial Data Engineering": {
      one: "Getting real spatial data into shape, at scale, correctly.",
      stack: ["PostGIS", "GeoPandas", "Shapely", "pyproj", "DuckDB spatial", "Apache Arrow", "MapLibre GL"],
      items: [
        { year: "2026", what: "KeyStone - Florida statewide cadastral File Geodatabase to 11,319 web-ready parcels: attribute push-down, EPSG:4326 reprojection, topology-preserving simplification, STRtree indexing." },
        { year: "2026", what: "FieldSurvey - PostGIS GiST indexes, geography-cast distance, KNN operator parcel snapping, Fisher-Jenks choropleth classification from scratch." },
        { year: "2026", what: "GeoChatBot - DuckDB-WASM spatial SQL over Apache Arrow in the browser, with exact-haversine macros replacing an inaccurate built-in." },
        { year: "Aug 2025 - Feb 2026", what: "iAdapt - FDOT District 5: review and comparative analysis of existing transport analyses for Central Florida." },
      ],
    },
    "Full-Stack Engineering": {
      one: "Shipping the whole system, not just the model.",
      stack: ["Next.js", "React", "FastAPI", "Supabase", "PostgreSQL", "Docker", "Vercel"],
      items: [
        { year: "2026", what: "KeyStone - FastAPI monolith plus a 12-function Vercel serverless port kept in lock-step by a CI-style parity test, live in production." },
        { year: "2026", what: "FieldSurvey - Next.js 15 app orchestrating a Supabase/PostGIS layer and two Python services through a cache-through compute layer." },
        { year: "2026", what: "Proxima - React Native/Expo client, FastAPI + OR-Tools backend, ~90-table multi-tenant Postgres with row-level security." },
        { year: "2026", what: "PetroTech Connect - ~125K LOC feature-sliced modular monolith with a wallet ledger, SSE real-time layer, and an ETL microservice." },
        { year: "2026", what: "Local Glean - 8-service Docker Compose stack with scheduled backups, restore drills, and Makefile-driven quality gates." },
      ],
    },
    "Computer Vision": {
      one: "Classification, detection, and segmentation on real imagery.",
      stack: ["PyTorch", "TensorFlow", "YOLOv5", "U-Net", "MobileNetV2"],
      items: [
        { year: "Fall 2022", what: "YOLOv5 - handwritten math symbol classification + object detection." },
        { year: "Spring 2024", what: "Applied ML - flower classification (MobileNetV2 / Xception) and U-Net lung X-ray segmentation." },
        { year: "Fall 2024", what: "Transfer learning on CIFAR-100 for built-environment feature detection." },
        { year: "2026", what: "Empirical study of PCA's effect on Logistic Regression vs. Random Forest on a ship image dataset." },
      ],
    },
    "Location-Based Services": {
      one: "Recommender systems that know where you are.",
      stack: ["Python", "scikit-learn", "PostGIS"],
      items: [
        { year: "2021", what: "First-authored - A Store Location-based Recommender System Based on User's Position and Web Searches (Journal of Location Based Services)." },
        { year: "2020 / ISPRS 2019", what: "Discover Points of Interest based on Users' Internet Searches through an Online Shopping Website." },
        { year: "2019", what: "MSc thesis at U Tehran on POI-aware recommenders using pattern recognition." },
      ],
    },
  },

  timeline: [
    { year: 2012, label: "Top 1% - Iran national university entrance" },
    { year: 2016, label: "BSc, Civil-Geomatics Engineering, KNTU" },
    { year: 2016, label: "Ranked 10th - national MSc entrance exam" },
    { year: 2017, label: "Joined LBS Lab, University of Tehran" },
    { year: 2019, label: "MSc, GIS, University of Tehran (thesis: Excellent)" },
    { year: 2020, label: "Coursera ML + Deep Learning Specialization" },
    { year: 2021, label: "Provost Graduate Support Funding, UF" },
    { year: 2022, label: "Began PhD, Design Construction & Planning, UF" },
    { year: 2023, label: "Began MSc, ECE, UF (dual degree)" },
    { year: 2024, label: "UF Machine Learning Certificate completed" },
    { year: 2025, label: "MSc ECE conferred - GPA 3.81" },
    { year: 2026, label: "PhD defended - GeoChatBot, Local Glean, KeyStone, FieldSurvey shipped" },
  ],
};
